services:
  njoy-account-service:
    env_file: ".env"
    image: njoy-account-service
    container_name: ${CONTAINER_NAME}
    restart: always
    volumes: 
      - /${VOLUME}/njoy-account-service/config:/njoy-account-service/config
      - /${VOLUME}/njoy-account-service/keys:/njoy-account-service/backend_shared/security/.keys
      - /${VOLUME}/njoy-account-service/logs:/njoy-account-service/logs
    ports:
      - ${API_PORT}:${API_PORT}

  db:
    env_file: ".env"
    image: mariadb:10.2
    restart: always
    volumes:
      - /${VOLUME}/njoy-account-service/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - ${DB_PORT}:3306